version: "3.1"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: altaycrossdb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    tty: true
    ports:
      - 3306:3306
    expose:
      - "3306"
    volumes:
      - ./db:/var/lib/mysql/


  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080


  server:
    build: ./server 
    volumes:
      - ./server:/server
    working_dir: /server
    restart: always
    ports:
      - 8000:8000
    environment:
      APP_DEBUG: 1
      LOG_CHANNEL: stack
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: altaycrossdb
    command: "php artisan serve --host=0.0.0.0 --port=8000"
#    command: "npm run watch"
    expose:
      - "8000" 
    depends_on:
      - db
